//////////////////////////////////////////////////////////////////////
// This file was automatically generated by CLIF to run under Python 3
// Version 0.3
//////////////////////////////////////////////////////////////////////
// source: /pykaldi/kaldi/base/kaldi-error.clif

#include <Python.h>

namespace __kaldi__error_clifwrap {

bool Ready();
PyObject* Init();

}  // namespace __kaldi__error_clifwrap

PyMODINIT_FUNC PyInit__kaldi_error(void) {
  if (!__kaldi__error_clifwrap::Ready()) return nullptr;
  return __kaldi__error_clifwrap::Init();
}
